-- AlterTable
ALTER TABLE "Photo" ALTER COLUMN "likes" DROP NOT NULL;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "otp" DROP NOT NULL,
ALTER COLUMN "otp" SET DATA TYPE TEXT,
ALTER COLUMN "otpExpiry" DROP NOT NULL;
